---@class biquge.Book
---@field author string
---@field link string
---@field title string
---
---@class biquge.Chapter
---@field link string
---@field title string
---@field content? string[] -- 本地文件章节内容
---@field start_line? integer -- 本地文件章节起始行号
---
---@class biquge.Location
---@field bufnr integer
---@field row integer
---
---@class biquge.Record
---@field info biquge.Book
---@field last_read integer
---@field is_local? boolean -- 标识是否为本地文件
---@field chapters? biquge.Chapter[] -- 本地文件的章节缓存
---@field reading_position? biquge.ReadingPosition -- 详细阅读位置

---@class biquge.ReadingPosition
---@field chapter_index integer -- 章节索引
---@field line_index integer -- 行索引（在当前章节内容中的位置）
---@field timestamp integer -- 最后阅读时间戳
---
---@class biquge.ReadingRecord
---@field info biquge.Book
---@field last_read integer
---@field is_local? boolean
---@field chapters? biquge.Chapter[]
---@field reading_position? biquge.ReadingPosition

---@class biquge.Config
---@field width integer
---@field height integer
---@field hlgroup string
---@field bookshelf string
---@field reading_history string -- 所有书籍阅读历史文件路径
---@field last_reading string -- 最后阅读记录文件路径
---@field picker "builtin"|"telescope"|"snacks"
---@field local_dir string -- 本地文件默认目录
---
---@alias biquge.picker.Action fun(picker:any, item: any)
---
---@class biquge.picker.Key
---@field [1] string
---@field mode string|string[]|nil
---
---@class biquge.picker.Opts
---@field items any[]
---@field display fun(item: any): string
---@field prompt? string
---@field confirm? biquge.picker.Action
---@field actions? table<string, biquge.picker.Action>
---@field keys? table<string, string|biquge.picker.Key>
