---@class biquge.Book
---@field author string
---@field link string
---@field title string
---
---@class biquge.Chapter
---@field link string
---@field title string
---
---@class biquge.Location
---@field bufnr integer
---@field row integer
---
---@class biquge.Record
---@field info biquge.Book
---@field last_read integer
---
---@class biquge.Config
---@field width integer
---@field height integer
---@field hlgroup string
---@field bookshelf string
---@field picker "builtin"|"telescope"|"snacks"
---
---@alias biquge.picker.Action fun(picker:any, item: any)
---
---@class biquge.picker.Key
---@field [1] string
---@field mode string|string[]|nil
---
---@class biquge.picker.Opts
---@field items any[]
---@field display fun(item: any): string
---@field prompt? string
---@field confirm? biquge.picker.Action
---@field actions? table<string, biquge.picker.Action>
---@field keys? table<string, string|biquge.picker.Key>
